CREATE TABLE COMMENTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_by INTEGER NOT NULL,
  created_at INTEGER DEFAULT (unixepoch()),
  updated_by INTEGER DEFAULT NULL,
  updated_at INTEGER DEFAULT NULL,
  FOREIGN KEY (item_id) REFERENCES ITEMS(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES USERS(id),
  FOREIGN KEY (updated_by) REFERENCES USERS(id)
);
