-- Add note_color columns to OPTIONS and STOCK_TRADES
ALTER TABLE OPTIONS ADD COLUMN note_color TEXT;
ALTER TABLE STOCK_TRADES ADD COLUMN note_color TEXT;
ALTER TABLE STOCK_TRADES ADD COLUMN close_note_color TEXT;
