ALTER TABLE OPTIONS ADD COLUMN has_separator BOOLEAN DEFAULT 0;
ALTER TABLE STOCK_TRADES ADD COLUMN has_separator BOOLEAN DEFAULT 0;
ALTER TABLE STOCK_TRADES ADD COLUMN close_has_separator BOOLEAN DEFAULT 0;
