-- Add group_id to OPTIONS and STOCK_TRADES tables
ALTER TABLE OPTIONS ADD COLUMN group_id INTEGER;
ALTER TABLE STOCK_TRADES ADD COLUMN group_id INTEGER;
ALTER TABLE STOCK_TRADES ADD COLUMN close_group_id INTEGER;
